# Site
name: "Tuyen Nguyen"
title: "My Blog"
description: "Grow yourself and develop with me!"
logo: 'assets/images/ava.png'
favicon: 'assets/images/ava.png'
# url: https://tuyen-nnt.github.io
url: https://tuyen-nnt.github.io
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: tuyendev96@gmail.com


# Authors
authors:
  tuyennnt:
    name: tuyennnt
    display_name: Tuyen
    avatar: 'assets/images/ava.png'
    email: tuyendev96@gmail.com
    web: https://www.tuyen-nnt.github.io
    twitter: ""
    description: "Author of this blog, mostly about Technical which is the field I am interested in."
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
